name: Hello GitHub Actions

on:
  push:   # Trigger workflow on every push event

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello GitHub Actions"
